name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      #      - uses: actions/setup-java@v3
      #        with:
      #          distribution: 'zulu'
      #          java-version: 17
      #      - run: java --version

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18
          java-package: jre
          cache: 'gradle'
      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
          check-latest: true
      - run: printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties
      - run: java --version

      - name: Gradle Check
        run: ./gradlew check -PtargetJava=19 --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: gradle/wrapper-validation-action@v1

      - name: Github Packages
        run: ./gradlew -PtargetJava=19 :pagerduty-event-json-iterator-adapter:publish :pagerduty-event-client:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
